import type { Theme } from "@/lib/types";

export const themes: Record<Theme, Record<string, string>> = {
  claude: {
    "--bg": "#1c1917",
    "--sidebar-bg": "#141210",
    "--input-bg": "#2c2925",
    "--accent": "#da8c1a",
    "--accent-hover": "#f0a030",
    "--text": "#f0ede8",
    "--text-muted": "#7c7168",
    "--bubble-user": "#2c2925",
    "--font": "var(--loaded-inter), sans-serif",
    "--font-heading": "Georgia, serif",
    "--border": "#3a3530",
    "--scrollbar": "#3a3530",
    "--radius-bubble": "18px",
    "--shadow-input": "0 0 0 1px #3a3530, 0 2px 8px rgba(0,0,0,0.4)",
  },
  gpt: {
    "--bg": "#ffffff",
    "--sidebar-bg": "#f9f9f9",
    "--input-bg": "#f4f4f4",
    "--accent": "#10a37f",
    "--accent-hover": "#0d8f6e",
    "--text": "#0d0d0d",
    "--text-muted": "#8e8ea0",
    "--bubble-user": "#f4f4f4",
    "--font": "var(--loaded-dm-sans), system-ui, sans-serif",
    "--font-heading": "inherit",
    "--border": "#ececec",
    "--scrollbar": "#d9d9e3",
    "--radius-bubble": "12px",
    "--shadow-input": "0 0 0 1px #d9d9e3",
  },
  grok: {
    "--bg": "#000000",
    "--sidebar-bg": "#0a0a0a",
    "--input-bg": "#0f0f0f",
    "--accent": "#e53935",
    "--accent-hover": "#ff5252",
    "--text": "#f5f5f5",
    "--text-muted": "#555",
    "--bubble-user": "#111",
    "--font": "var(--loaded-ibm-mono), monospace",
    "--font-heading": "var(--loaded-ibm-sans), sans-serif",
    "--border": "#1f1f1f",
    "--scrollbar": "#1f1f1f",
    "--radius-bubble": "6px",
    "--shadow-input": "0 0 0 1px #1f1f1f",
  },
};

export const THEME_ACCENTS: Record<Theme, string> = {
  claude: "#da8c1a",
  gpt: "#10a37f",
  grok: "#e53935",
};
